server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_stumanage?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: zhu980122

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    cn:
      sm:
        mapper: debug
